# COMMANDS TO CREATE THE DEV ENVORINMENT USING DOCKER COMPOSE
# docker-compose -f ./Docker/dev-env-compose.yml run app rails new . --force --api --skip-bundle
# docker-compose -f ./Docker/dev-env-compose.yml build
# docker-compose -f ./Docker/dev-env-compose.yml up
# the server has to be running to run any other command like bundle install or generate an instalation for rspec
version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: noteapp
  #     MYSQL_USER: appuser
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3307:3306"
  db:
    image: "postgres:latest"
    restart: always
    # ports: 
    #   - "8000:5432"
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
  app:
    build: ..
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "..:/app"
    ports:
      - "3929:3000"
    environment:
      DB_HOST: db
      DB_USER: example
      DB_PASSWORD: example
    depends_on:
      - db
    links:
      - db
    # environment:
    #   DB_USER: root
    #   DB_NAME: noteapp
    #   DB_PASSWORD: password
    #   DB_HOST: db