# COMMANDS TO CREATE THE DEV ENVORINMENT USING DOCKER COMPOSE
# docker-compose -f ./Docker/dev-env-compose.yml run app rails new . --force --api --skip-bundle
# docker-compose -f ./Docker/dev-env-compose.yml build
# docker-compose -f ./Docker/dev-env-compose.yml up
version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: noteapp
  #     MYSQL_USER: appuser
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3307:3306"
  app:
    build: ..
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - "..:/app"
    ports:
      - "3929:3000"
    # depends_on:
    #   - db
    # links:
    #   - db
    # environment:
    #   DB_USER: root
    #   DB_NAME: noteapp
    #   DB_PASSWORD: password
    #   DB_HOST: db