---
openapi: 3.0.1
info:
  title: Shopping List API
  version: v1
paths: 
  /categories:
    get:
      summary: Returns the list of all the categories
      description: Endpoint to get all the available categories
      responses:
        '200':
          description: An array of JSON objects with each category
          content:
            application/json:
              schema: 
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1234
                        name:
                          type: string
                          example: Sample Category
                        description:
                          type: string
                          example: This is a sample category
                        created_at:
                          type: string
                          format: datetime
                          example: '2022-10-21T01:52:44.530Z'
                        updated_at:
                          type: string
                          format: datetime
                          example: '2022-10-21T01:52:44.530Z'

    post:
      summary: Creates a category
      description: Endpoint to create a category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Sample Category 2
                    description:
                      type: string
                      example: This is the second sample category
      responses:
        '201':
          description: A JSON object with the status
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    example: created
                  category_id:
                    type: int
                    format: int32
                    example: 1234
        '400':
          description: Returns the api error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: This is the error generated in the API
  /categories/{category_id}:
    get:
      summary: Returns the information for a specific category
      description: Endpoint to get information on one category
      parameters:
        - name: category_id
          in: path
          required: true
          description: A number indicating the ID of the category
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: An object with the information for the specified category
          content:
            application/json:
              schema: 
                type: object
                properties:
                  category:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1234
                      name:
                        type: string
                        example: Sample Category
                      description:
                        type: string
                        example: This is a sample category
                      created_at:
                        type: string
                        format: datetime
                        example: '2022-10-21T01:52:44.530Z'
                      updated_at:
                        type: string
                        format: datetime
                        example: '2022-10-21T01:52:44.530Z'
        '400':
          description: Returns the api error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: This is the error generated in the API

    put:
      summary: Updates the information of an specific category
      description: Endpoint to update the information on one category
      parameters:
        - name: category_id
          in: path
          required: true
          description: A number indicating the ID of the category
          schema:
            type : integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                category:
                  type: object
                  properties:
                    name:
                      required: false
                      type: string
                      example: Sample Category 2
                    description:
                      required: false
                      type: string
                      example: This is the second sample category
      responses:
        '201':
          description: An JSON object with the status
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    example: updated
                  category_id:
                    type: int
                    format: int32
                    example: 1234
        '400':
          description: Returns the api error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: This is the error generated in the API
    delete:
      summary: Deletes an specific category
      description: Endpoint to delete one category
      parameters:
        - name: category_id
          in: path
          required: true
          description: A number indicating the ID of the category
          schema:
            type : integer
            format: int64
            minimum: 1
      responses:
        '201':
          description: An JSON object with the status
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    example: deleted
        '400':
          description: Returns the api error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: This is the error generated in the API
  /prices:
    get:

# servers:
# - url: http://localhost:3929
#   variables:
#     defaultHost:
#       default: www.example.com
