# SEED DATA FOR THE PRICE MODEL

Price.delete_all

Price.create!({product_id: Product.where(name:"Axion Loza Limon")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 13800})
Price.create!({product_id: Product.where(name:"Axion Loza Limon")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 15050})
Price.create!({product_id: Product.where(name:"Protex Avena")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 9600})
Price.create!({product_id: Product.where(name:"Protex Avena")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 9450})
Price.create!({product_id: Product.where(name:"Jabon Chiqui")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 23200})
Price.create!({product_id: Product.where(name:"Jabon Chiqui")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 22300})
Price.create!({product_id: Product.where(name:"Oreo Chocolate")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 8450})
Price.create!({product_id: Product.where(name:"Oreo Chocolate")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 8500})
Price.create!({product_id: Product.where(name:"Alpin Chocolate Bolsas individuales")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 9950})
Price.create!({product_id: Product.where(name:"Alpin Chocolate Bolsas individuales")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 12300})
Price.create!({product_id: Product.where(name:"Yogo yogo bolsa 150ml")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 8300})
Price.create!({product_id: Product.where(name:"Yogo yogo bolsa 150ml")[0].id , store_id: Store.where(name: "Olimpica")[0].id, price: 8300})
Price.create!({product_id: Product.where(name:"Yogo yogo bolsa 150ml")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 8700})
Price.create!({product_id: Product.where(name:"Yogurt M&M")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 4400})
Price.create!({product_id: Product.where(name:"Country Hill")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 5800})
Price.create!({product_id: Product.where(name:"Country Hill")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6100})
Price.create!({product_id: Product.where(name:"Quesito Alpina")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 4450})
Price.create!({product_id: Product.where(name:"Quesito Alpina")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 5000})
Price.create!({product_id: Product.where(name:"Quesito Alpina")[0].id , store_id: Store.where(name: "D1")[0].id, price: 4890})
Price.create!({product_id: Product.where(name:"Arepas Dona paisa con sal")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 5300})
Price.create!({product_id: Product.where(name:"Arepas Dona paisa sin sal")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 4300})
Price.create!({product_id: Product.where(name:"Palitos de Queso Zenu")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 17750})
Price.create!({product_id: Product.where(name:"Empanadas Pollo Zenu")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 26400})
Price.create!({product_id: Product.where(name:"Empanadas Pollo Zenu")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 22700})
Price.create!({product_id: Product.where(name:"Lasagna Zenu")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 13000})
Price.create!({product_id: Product.where(name:"Cocositos Bimbo")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 1600})
Price.create!({product_id: Product.where(name:"Leche Deslactosada Alpina Bolsa 1100ml")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 27950})
Price.create!({product_id: Product.where(name:"Leche Deslactosada Alpina Bolsa 1100ml")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 24900})
Price.create!({product_id: Product.where(name:"Leche Deslactosada Alpina Bolsa 1300ml")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 27900})
Price.create!({product_id: Product.where(name:"Leche Deslactosada Alqueria Bolsa 1100ml")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 29150})
Price.create!({product_id: Product.where(name:"Leche Deslactosada Alqueria Bolsa 1300ml")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 27100})
Price.create!({product_id: Product.where(name:"Choquis bolitas")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 15700})
Price.create!({product_id: Product.where(name:"Choquis bolitas")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 13500})
Price.create!({product_id: Product.where(name:"Kumis Alpina")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 11200})
Price.create!({product_id: Product.where(name:"Kumis Alpina")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 17800})
Price.create!({product_id: Product.where(name:"Kumis Lacti")[0].id , store_id: Store.where(name: "D1")[0].id, price: 6990})
Price.create!({product_id: Product.where(name:"Papas Rusticas Mcain")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 17350})
Price.create!({product_id: Product.where(name:"Papas Rusticas Mcain")[0].id , store_id: Store.where(name: "Exito")[0].id, price: 12450})
Price.create!({product_id: Product.where(name:"Jabon Jhonson & Jhonson Avena")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 8950})
Price.create!({product_id: Product.where(name:"Jabon Loza Crem Limon Blancox")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 13200})
Price.create!({product_id: Product.where(name:"Alpin Fresa Bolsa Individual")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 11350})
Price.create!({product_id: Product.where(name:"Alpin Mix Bolsa Individual")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 11250})
Price.create!({product_id: Product.where(name:"Alpin Mix Bolsa Individual")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 11500})
Price.create!({product_id: Product.where(name:"Lucky charms")[0].id , store_id: Store.where(name: "Colsubsidio")[0].id, price: 15500})
Price.create!({product_id: Product.where(name:"Servilletas familia")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 7500})
Price.create!({product_id: Product.where(name:"Papel Higienico Familia")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 21550})
Price.create!({product_id: Product.where(name:"Scott Cocina")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 23800})
Price.create!({product_id: Product.where(name:"Pañitos Humedos")[0].id , store_id: Store.where(name: "D1")[0].id, price: 4590})
Price.create!({product_id: Product.where(name:"Rosquitas")[0].id , store_id: Store.where(name: "D1")[0].id, price: 5850})
Price.create!({product_id: Product.where(name:"Pan Tajado Horneaditos")[0].id , store_id: Store.where(name: "D1")[0].id, price: 2750})
Price.create!({product_id: Product.where(name:"Pan Tajado Bimbo")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6500})
Price.create!({product_id: Product.where(name:"Pan Tajado Bimbo")[0].id , store_id: Store.where(name: "Exito")[0].id, price: 5490})
Price.create!({product_id: Product.where(name:"Jamon Pavo")[0].id , store_id: Store.where(name: "D1")[0].id, price: 13650})
Price.create!({product_id: Product.where(name:"Mani Crunchy")[0].id , store_id: Store.where(name: "D1")[0].id, price: 6150})
Price.create!({product_id: Product.where(name:"Mani Salado")[0].id , store_id: Store.where(name: "D1")[0].id, price: 3350})
Price.create!({product_id: Product.where(name:"Mani Mezcla Divertida")[0].id , store_id: Store.where(name: "D1")[0].id, price: 4150})
Price.create!({product_id: Product.where(name:"Lomo de Res")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 58000})
Price.create!({product_id: Product.where(name:"Lomo de Cerdo")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 25800})
Price.create!({product_id: Product.where(name:"Pechuga Fileteada")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 22000})
Price.create!({product_id: Product.where(name:"Choripaco Ahumado")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 22800})
Price.create!({product_id: Product.where(name:"Arroz Florhuila")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 37800})
Price.create!({product_id: Product.where(name:"Gaseosa Postobon Botella 3L")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 9950})
Price.create!({product_id: Product.where(name:"Salchicha Perro Zenu")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6100})
Price.create!({product_id: Product.where(name:"Queso Mozarela Tajado 400gr")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 19200})
Price.create!({product_id: Product.where(name:"Queso Campesino Colanta")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6750})
Price.create!({product_id: Product.where(name:"Arepa Arepaisa Paquete 450gr")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 2000})
Price.create!({product_id: Product.where(name:"Palitos de queso Paquete 125gr")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 7100})
Price.create!({product_id: Product.where(name:"Torta de Chocolate")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6800})
Price.create!({product_id: Product.where(name:"Pinguinos")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 7400})
Price.create!({product_id: Product.where(name:"Tornillos Doria")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 1950})
Price.create!({product_id: Product.where(name:"Mermelada frutos Rojos San Jorge")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 5800})
Price.create!({product_id: Product.where(name:"Mezcla Pancakes Tia Jemina")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 4450})
Price.create!({product_id: Product.where(name:"Doña Arepa")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 2050})
Price.create!({product_id: Product.where(name:"Harina de Trigo")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 1750})
Price.create!({product_id: Product.where(name:"Maggi Boloñesa Sobre Individual")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 3200})
Price.create!({product_id: Product.where(name:"Salsa Soya Coruña")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 8100})
Price.create!({product_id: Product.where(name:"Atun aceite Lata Individual")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 12400})
Price.create!({product_id: Product.where(name:"Galletas Festival recreo")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 9900})
Price.create!({product_id: Product.where(name:"Chokis galletas")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 6500})
Price.create!({product_id: Product.where(name:"Hit de Naranja")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 3900})
Price.create!({product_id: Product.where(name:"Hit Mora, mango, frutos tropicales")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 2950})
Price.create!({product_id: Product.where(name:"Choco Krispis")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 12900})
Price.create!({product_id: Product.where(name:"Ponque Gala Chocolate")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 7450})
Price.create!({product_id: Product.where(name:"Tostacos")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 9100})
Price.create!({product_id: Product.where(name:"Waffle Forno")[0].id , store_id: Store.where(name: "Comunal")[0].id, price: 23900})
Price.create!({product_id: Product.where(name:"Arracacha")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 4800})
Price.create!({product_id: Product.where(name:"Arveja desgranada")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 22000})
Price.create!({product_id: Product.where(name:"Banano Uraba")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 3000})
Price.create!({product_id: Product.where(name:"Cebolla Cabezona Roja")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 3400})
Price.create!({product_id: Product.where(name:"Cebolla Cabezona")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 3000})
Price.create!({product_id: Product.where(name:"Cebolla Larga")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 5700})
Price.create!({product_id: Product.where(name:"Limón Tahiti")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 3000})
Price.create!({product_id: Product.where(name:"Manzana Royal")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 1600})
Price.create!({product_id: Product.where(name:"Manzana Verde")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 1900})
Price.create!({product_id: Product.where(name:"Papa Pastusa ")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 9200})
Price.create!({product_id: Product.where(name:"Papaya")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 3500})
Price.create!({product_id: Product.where(name:"Promocion Pulpas Paquete individual")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 10000})
Price.create!({product_id: Product.where(name:"Tomate Chonto")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 6200})
Price.create!({product_id: Product.where(name:"Zanahoria")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 4200})
Price.create!({product_id: Product.where(name:"Zumo de Limon")[0].id , store_id: Store.where(name: "Fruvar")[0].id, price: 4000})
Price.create!({product_id: Product.where(name:"Hamburguesa Porchi")[0].id , store_id: Store.where(name: "Exito")[0].id, price: 19100})

puts "Created #{Price.count} prices"