# SEED DATA FOR THE PRODUCT MODEL

Product.delete_all

Product.create!({name: "Axion Loza Limon" , quantity: "1500ml", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Protex Avena" , quantity: "3 uni", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Jabon Chiqui" , quantity: "400ml", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Oreo Chocolate" , quantity: "", category_id: Category.where(name: "Galletas")[0].id})
Product.create!({name: "Alpin Chocolate Bolsas individuales" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Yogo yogo bolsa 150ml" , quantity: "8uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Yogurt M&M" , quantity: "2uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Country Hill" , quantity: "1000ml", category_id: Category.where(name: "Jugos")[0].id})
Product.create!({name: "Quesito Alpina" , quantity: "185gr", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Arepas Dona paisa con sal" , quantity: "10uni", category_id: Category.where(name: "Arepas")[0].id})
Product.create!({name: "Arepas Dona paisa sin sal" , quantity: "10uni", category_id: Category.where(name: "Arepas")[0].id})
Product.create!({name: "Palitos de Queso Zenu" , quantity: "26uni", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Empanadas Pollo Zenu" , quantity: "30uni", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Lasagna Zenu" , quantity: "1uni", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Cocositos Bimbo" , quantity: "2uni", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Leche Deslactosada Alpina Bolsa 1100ml" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Leche Deslactosada Alpina Bolsa 1300ml" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Leche Deslactosada Alqueria Bolsa 1100ml" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Leche Deslactosada Alqueria Bolsa 1300ml" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Choquis bolitas" , quantity: "12uni", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Kumis Alpina" , quantity: "1000ml", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Kumis Alpina" , quantity: "1750ml", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Kumis Lacti" , quantity: "1000ml", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Papas Rusticas Mcain" , quantity: "1 Kgr", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Jabon Jhonson & Jhonson Avena" , quantity: "3uni", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Jabon Loza Crem Limon Blancox" , quantity: "720ml", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Alpin Fresa Bolsa Individual" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Alpin Mix Bolsa Individual" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Lucky charms" , quantity: "", category_id: Category.where(name: "Cereales")[0].id})
Product.create!({name: "Servilletas familia" , quantity: "", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Papel Higienico Familia" , quantity: "12uni", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Scott Cocina" , quantity: "3uni", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Pañitos Humedos" , quantity: "72uni", category_id: Category.where(name: "Aseo")[0].id})
Product.create!({name: "Rosquitas" , quantity: "12uni", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Pan Tajado Horneaditos" , quantity: "450gr", category_id: Category.where(name: "Panaderia")[0].id})
Product.create!({name: "Pan Tajado Bimbo" , quantity: "600gr", category_id: Category.where(name: "Panaderia")[0].id})
Product.create!({name: "Jamon Pavo" , quantity: "227gr", category_id: Category.where(name: "Carnes Frias")[0].id})
Product.create!({name: "Mani Crunchy" , quantity: "200gr", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Mani Salado" , quantity: "200gr", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Mani Mezcla Divertida" , quantity: "200gr", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Lomo de Res" , quantity: "500gr", category_id: Category.where(name: "Carne")[0].id})
Product.create!({name: "Lomo de Cerdo" , quantity: "500gr", category_id: Category.where(name: "Carne")[0].id})
Product.create!({name: "Pechuga Fileteada" , quantity: "500gr", category_id: Category.where(name: "Carne")[0].id})
Product.create!({name: "Choripaco Ahumado" , quantity: "6uni", category_id: Category.where(name: "Carnes Frias")[0].id})
Product.create!({name: "Arroz Florhuila" , quantity: "10Kg", category_id: Category.where(name: "Granos")[0].id})
Product.create!({name: "Gaseosa Postobon Botella 3L" , quantity: "2uni", category_id: Category.where(name: "Gaseosas")[0].id})
Product.create!({name: "Salchicha Perro Zenu" , quantity: "240gr", category_id: Category.where(name: "Carnes Frias")[0].id})
Product.create!({name: "Queso Mozarela Tajado 400gr" , quantity: "25Tajadas", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Queso Campesino Colanta" , quantity: "250gr", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Arepa Arepaisa Paquete 450gr" , quantity: "5uni", category_id: Category.where(name: "Arepas")[0].id})
Product.create!({name: "Palitos de queso Paquete 125gr" , quantity: "6uni", category_id: Category.where(name: "Lacteos")[0].id})
Product.create!({name: "Torta de Chocolate" , quantity: "500gr", category_id: Category.where(name: "Panaderia")[0].id})
Product.create!({name: "Pinguinos" , quantity: "12uni", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Tornillos Doria" , quantity: "500gr", category_id: Category.where(name: "Pasta")[0].id})
Product.create!({name: "Mermelada frutos Rojos San Jorge" , quantity: "400gr", category_id: Category.where(name: "Salsas")[0].id})
Product.create!({name: "Mezcla Pancakes Tia Jemina" , quantity: "250gr", category_id: Category.where(name: "Harinas")[0].id})
Product.create!({name: "Doña Arepa" , quantity: "500gr", category_id: Category.where(name: "Harinas")[0].id})
Product.create!({name: "Harina de Trigo" , quantity: "500gr", category_id: Category.where(name: "Harinas")[0].id})
Product.create!({name: "Maggi Boloñesa Sobre Individual" , quantity: "1uni", category_id: Category.where(name: "Salsas")[0].id})
Product.create!({name: "Salsa Soya Coruña" , quantity: "500 ml", category_id: Category.where(name: "Salsas")[0].id})
Product.create!({name: "Atun aceite Lata Individual" , quantity: "3uni", category_id: Category.where(name: "Enlatados")[0].id})
Product.create!({name: "Galletas Festival recreo" , quantity: "18uni", category_id: Category.where(name: "Galletas")[0].id})
Product.create!({name: "Chokis galletas" , quantity: "6uni", category_id: Category.where(name: "Galletas")[0].id})
Product.create!({name: "Hit de Naranja" , quantity: "1L", category_id: Category.where(name: "Jugos")[0].id})
Product.create!({name: "Hit Mora, mango, frutos tropicales" , quantity: "1L", category_id: Category.where(name: "Jugos")[0].id})
Product.create!({name: "Choco Krispis" , quantity: "400gr", category_id: Category.where(name: "Cereales")[0].id})
Product.create!({name: "Ponque Gala Chocolate" , quantity: "400gr", category_id: Category.where(name: "Panaderia")[0].id})
Product.create!({name: "Tostacos" , quantity: "12uni", category_id: Category.where(name: "Chucherias")[0].id})
Product.create!({name: "Waffle Forno" , quantity: "525gr", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Arracacha" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Arveja desgranada" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Banano Uraba" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Cebolla Cabezona Roja" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Cebolla Cabezona" , quantity: "Paquete", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Cebolla Larga" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Limón Tahiti" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Manzana Royal" , quantity: "Unidad", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Manzana Verde" , quantity: "Unidad", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Papa Pastusa " , quantity: "5Lb", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Papaya" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Promocion Pulpas Paquete individual" , quantity: "4uni", category_id: Category.where(name: "Congelados")[0].id})
Product.create!({name: "Tomate Chonto" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Zanahoria" , quantity: "1Kg", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Zumo de Limon" , quantity: "335ml", category_id: Category.where(name: "Fruvar")[0].id})
Product.create!({name: "Hamburguesa Porchi" , quantity: "1010gr", category_id: Category.where(name: "Congelados")[0].id})

puts "Created #{Product.count} products"